services:
  - name: BlazorWasm-api
    type: web
    runtime: docker
    region: oregon
    plan: free
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
